### ISSUE TITLE
Why the code forces the user to define "redirectUrlTemplate"?

### ISSUE THREAD

**Issue by vitorbaptista** [mpneuried/aws-s3-form#9]
I'm still learning my way around S3, but it doesn't seem that `success_action_redirect` is required, right? However, if I don't define it or a `redirectUrlTemplate`, the code fails with:

```
/home/vitor/Projetos/okfn/opentrials/opentrials/node_modules/mpbasic/index.js:297
          throw _err;
          ^

ENOREDIR: You have to define a `redirectUrlTemplate` as config or `.create()` option.
    at AwsS3Form.Basic._handleError (/home/vitor/Projetos/okfn/opentrials/opentrials/node_modules/mpbasic/index.js:275:18)
    at AwsS3Form._handleError (/home/vitor/Projetos/okfn/opentrials/opentrials/node_modules/mpbasic/index.js:4:59)
    at AwsS3Form._redirectUrl (/home/vitor/Projetos/okfn/opentrials/opentrials/node_modules/aws-s3-form/lib/aws-s3-form.js:323:21)
    at AwsS3Form._redirectUrl (/home/vitor/Projetos/okfn/opentrials/opentrials/node_modules/aws-s3-form/lib/aws-s3-form.js:3:59)
    at AwsS3Form.policy (/home/vitor/Projetos/okfn/opentrials/opentrials/node_modules/aws-s3-form/lib/aws-s3-form.js:213:78)
    at AwsS3Form.policy (/home/vitor/Projetos/okfn/opentrials/opentrials/node_modules/aws-s3-form/lib/aws-s3-form.js:3:59)
    at Object.<anonymous> (/home/vitor/Projetos/okfn/opentrials/opentrials/foo.js:15:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```

**Comment by mpneuried** [comment]
Hi,i checked the code again.
Since Version 0.3.x the redirect url is no longer required.
See https://github.com/mpneuried/aws-s3-form/commit/dc326ab3393cb1c7321ce3477cf42ee50a6d3fad
Instead there is a fallback to `success_action_status` with code `204`.
But the option `redirectUrlTemplate` has to be `undefined` or `null`.
You can also define your prefered `successActionStatus` value.

Which version do you use?
FYI: I updated the module to version `0.3.4` with updated dependencies.

To play with the uploader you can clone the repo and start the testserver.
See the [optimized docs](https://github.com/mpneuried/aws-s3-form#play-with-it-)

**Comment by mpneuried** [comment]
Does this help to solve your problem?
